name: rick_morty
description: "A project to fulfill the requirements of the Flutter Developer Internship at BIGIO."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.4.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  skeletonizer: ^1.4.2
  auto_route: ^9.2.1+1
  intl: ^0.19.0
  injectable: ^2.4.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.6.0
  icons_launcher: ^2.1.7
  isar_generator: ^3.1.0+1

dependency_overrides:
  analyzer: ^6.2.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  generate: true
  uses-material-design: true
